---
title: "Identificacion DMR Genero"
author: "Ana Diez Borge"
date: "7 de diciembre de 2020"
output: html_document
---

```{r Cargamos datos de metilación}
Data_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio"
Results_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio/Results"
setwd(Data_dir)
coad_data = readRDS(file = "coad_data.RDS")
lihc_data = readRDS(file = "lihc_data.RDS")
paad_data = readRDS(file = "paad_data.RDS")
luad_data = readRDS(file = "luad_data.RDS")
```

```{r filtrado de muestras}
#Las sondas que están a 0, 1 o 2 nucleótidos de la metilcitosina de interés muestran una distribución marcadamente diferente a las más lejanas en el tejido sano. Por esto, para evitar la confusión se eliminan las sondas que estan a una distancia de 2 nucleotidos o menos de una CpG cuya frecuencia alélica menor sea igual a 0.05
library(DMRcate)
nrow(assay(paad_data))
paad_data_noSNPs <- paad_data
paad_data.noSNPs <- rmSNPandCH(assay(paad_data_noSNPs), dist=2, mafcut=0.05)
assay(paad_data_noSNPs, withDimnames=FALSE) <- paad_data.noSNPs
nrow(paad_data.noSNPs)
```

```{r}
paad_data_noSNPs <- paad_data
assay(paad_data_noSNPs) <- paad_data.noSNPs
```


```{r Transformamos beta-values a M-values}
#En este caso para aumentar la fiabilidad del estudio se transforman los b-value a M-value
#Para obtener los M-values creo una la funcion mvalues
mvalues <- function(bvalue) {
      m <- log2(bvalue/(1 - bvalue))
      return(m)}

paad_mvalues <- apply(assay(paad_data), c(1,2), mvalues)
lihc_mvalues <- apply(assay(lihc_data), c(1,2), mvalues)
coad_mvalues <- apply(assay(coad_data), c(1,2), mvalues)
luad_mvalues <- apply(assay(luad_data), c(1,2), mvalues)

paad_data_m <- paad_data
lihc_data_m <- lihc_data
coad_data_m <- coad_data
luad_data_m <- luad_data

assay(paad_data_m) = paad_mvalues
assay(lihc_data_m) = lihc_mvalues
assay(coad_data_m) = coad_mvalues
assay(luad_data_m) = luad_mvalues
```


##Matriz modelo y diferencial
```{r PAAD}
library(DMRcate)
type_paad <- factor(paad_data_m$definition)
gender_paad <- factor(paad_data_m$gender)
design_paad <- model.matrix(~type_paad:gender_paad)
myannotation_paad <- cpg.annotate("array", assay(paad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_paad, coef=2)

dmrcoutput_paad <- dmrcate(myannotation_paad, lambda=1000, C=2)

results.ranges_paad <- extractRanges(dmrcoutput_paad, genome = "hg19")

groups_paad <- c(female="magenta", male="forestgreen", "Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue" )
cols_paad <- groups_paad[as.character(type_paad)]
DMR.plot(ranges=results.ranges_paad, dmr=3, CpGs=assay(paad_data_m), what="M",
arraytype = "450K", phen.col=cols_paad, genome="hg19")

library(missMethyl)
enrichment_GO_paad <- goregion(results.ranges_paad, all.cpg = rownames(paad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_paad <- enrichment_GO_paad[order(enrichment_GO_paad$P.DE),]
head(as.matrix(enrichment_GO_paad), 10)
```

```{r LIHC}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_lihc <- factor(lihc_data_m$definition)
gender_lihc <- factor(lihc_data_m$gender)
design_lihc <- model.matrix(~type_lihc:gender_lihc)
myannotation_lihc <- cpg.annotate("array", assay(lihc_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_lihc, coef=2)

dmrcoutput_lihc <- dmrcate(myannotation_lihc, lambda=1000, C=2)

results.ranges_lihc <- extractRanges(dmrcoutput_lihc, genome = "hg19")
results.ranges_coad[c(1:5), c(1,5,8)]

groups_lihc <- c(female="magenta", male="forestgreen", "Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue" )
cols_lihc <- groups_lihc[as.character(type_lihc)]
DMR.plot(ranges=results.ranges_lihc, dmr=6, CpGs=assay(lihc_data_m), what="M",
arraytype = "450K", phen.col=cols_lihc, genome="hg19")

enrichment_GO_lihc <- goregion(results.ranges_lihc, all.cpg = rownames(lihc_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_lihc <- enrichment_GO_lihc[order(enrichment_GO_lihc$P.DE),]
head(as.matrix(enrichment_GO_lihc), 10)
```

```{r COAD}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_coad <- factor(coad_data_m$definition)
gender_coad <- factor(coad_data_m$gender)
design_coad <- model.matrix(~type_coad:gender_coad)
myannotation_coad <- cpg.annotate("array", assay(coad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_coad, coef=2)

dmrcoutput_coad <- dmrcate(myannotation_coad, lambda=1000, C=2)

results.ranges_coad <- extractRanges(dmrcoutput_coad, genome = "hg19")
results.ranges_coad

groups_coad <- c(male="magenta", female="forestgreen","Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_coad <- groups_coad[as.character(type_coad)]
DMR.plot(ranges=results.ranges_coad, dmr=1000, CpGs=assay(coad_data), what="M",
arraytype = "450K", phen.col=cols_coad, genome="hg19")

enrichment_GO_coad <- goregion(results.ranges_coad, all.cpg = rownames(coad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_coad <- enrichment_GO_coad[order(enrichment_GO_coad$P.DE),]
head(as.matrix(enrichment_GO_coad), 10)
```

```{r LUAD}
#BiocManager::install("DMRcate")
library(DMRcate)
type_luad <- factor(luad_data_m$definition)
gender_luad <- factor(luad_data_m$gender)
design_luad <- model.matrix(~type_luad:gender_luad)
myannotation_luad <- cpg.annotate("array", assay(luad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_luad, coef=2)

dmrcoutput_luad <- dmrcate(myannotation_luad, lambda=1000, C=2)

results.ranges_luad <- extractRanges(dmrcoutput_luad, genome = "hg19")
results.ranges_luad
results.ranges_luad[c(1:5), c(1,5,8)]

groups_luad <- c(male="magenta", female="forestgreen","Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_luad <- groups_luad[as.character(type_luad)]
DMR.plot(ranges=results.ranges_luad, dmr=1, CpGs=assay(luad_data), what="M",
arraytype = "450K", phen.col=cols_luad, genome="hg19")

library(missMethyl)
enrichment_GO_luad <- goregion(results.ranges_luad, all.cpg = rownames(luad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_luad <- enrichment_GO_luad[order(enrichment_GO_luad$P.DE),]
head(as.matrix(enrichment_GO_luad), 10)
```











