---
title: "Identificación DMR tumor vs normal"
author: "Ana Diez Borge"
date: "13 de diciembre de 2020"
output: html_document
---

```{r Cargamos datos de metilación}
Data_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio"
Results_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio/Results"
setwd(Data_dir)
coad_data = readRDS(file = "coad_data.RDS")
lihc_data = readRDS(file = "lihc_data.RDS")
paad_data = readRDS(file = "paad_data.RDS")
luad_data = readRDS(file = "luad_data.RDS")
```

```{r Transformamos beta-values a M-values}
#En este caso para aumentar la fiabilidad del estudio se transforman los b-value a M-value
#Para obtener los M-values creo una la funcion mvalues
mvalues <- function(bvalue) {
      m <- log2(bvalue/(1 - bvalue))
      return(m)}

paad_mvalues <- apply(assay(paad_data), c(1,2), mvalues)
lihc_mvalues <- apply(assay(lihc_data), c(1,2), mvalues)
coad_mvalues <- apply(assay(coad_data), c(1,2), mvalues)
luad_mvalues <- apply(assay(luad_data), c(1,2), mvalues)

paad_data_m <- paad_data
lihc_data_m <- lihc_data
coad_data_m <- coad_data
luad_data_m <- luad_data

assay(paad_data_m) = paad_mvalues
assay(lihc_data_m) = lihc_mvalues
assay(coad_data_m) = coad_mvalues
assay(luad_data_m) = luad_mvalues
```


##Matriz modelo y diferencial
```{r PAAD}
library(DMRcate)
type_paad_tn <- factor(paad_data_m$definition)
design_paad_tn <- model.matrix(~type_paad_tn)
myannotation_paad_tn <- cpg.annotate("array", assay(paad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_paad_tn, coef=2)

dmrcoutput_paad_tn <- dmrcate(myannotation_paad_tn, lambda=1000, C=2)

results.ranges_paad_tn <- extractRanges(dmrcoutput_paad_tn, genome = "hg19")
results.ranges_paad_tn[,c(1,5,8)]

groups_paad_tn <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_paad_tn <- groups_paad_tn[as.character(type_paad_tn)]
DMR.plot(ranges=results.ranges_paad_tn, dmr=3, CpGs=assay(paad_data_m), what="M",
arraytype = "450K", phen.col=cols_paad_tn, genome="hg19")

library(missMethyl)
enrichment_GO_paad_tn <- goregion(results.ranges_paad_tn, all.cpg = rownames(paad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_paad_tn <- enrichment_GO_paad_tn[order(enrichment_GO_paad_tn$P.DE),]
head(as.matrix(enrichment_GO_paad_tn), 10)
```


```{r LIHC}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_lihc_tn <- factor(lihc_data_m$definition)
design_lihc_tn <- model.matrix(~type_lihc_tn)
myannotation_lihc_tn <- cpg.annotate("array", assay(lihc_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_lihc_tn, coef=2)

dmrcoutput_lihc_tn <- dmrcate(myannotation_lihc_tn, lambda=1000, C=2)

results.ranges_lihc_tn <- extractRanges(dmrcoutput_lihc_tn, genome = "hg19")
results.ranges_lihc_tn[c(1:5), c(1,5,8)]

groups_lihc_tn <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_lihc_tn <- groups_lihc_tn[as.character(type_lihc_tn)]
DMR.plot(ranges=results.ranges_lihc_tn, dmr=250, CpGs=assay(lihc_data_m), what="M",
arraytype = "450K", phen.col=cols_lihc_tn, genome="hg19")

enrichment_GO_lihc_tn <- goregion(results.ranges_lihc_tn, all.cpg = rownames(lihc_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_lihc_tn <- enrichment_GO_lihc_tn[order(enrichment_GO_lihc_tn$P.DE),]
head(as.matrix(enrichment_GO_lihc_tn), 10)
```

```{r COAD}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_coad_tn <- factor(coad_data_m$definition)
design_coad_tn <- model.matrix(~type_coad_tn)
myannotation_coad_tn <- cpg.annotate("array", assay(coad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_coad_tn, coef=2)
myannotation_coad_tn

dmrcoutput_coad_tn <- dmrcate(myannotation_coad_tn, lambda=1000, C=2)

results.ranges_coad_tn <- extractRanges(dmrcoutput_coad_tn, genome = "hg19")
results.ranges_coad_tn#[c(1:5),c(1,5,8)]

groups_coad_tn <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_coad_tn <- groups_coad_tn[as.character(type_coad_tn)]
DMR.plot(ranges=results.ranges_coad_tn, dmr=12349, CpGs=assay(coad_data_m), what="M",
arraytype = "450K", phen.col=cols_coad_tn, genome="hg19")

enrichment_GO_coad_tn <- goregion(results.ranges_coad_tn, all.cpg = rownames(coad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_coad_tn <- enrichment_GO_coad_tn[order(enrichment_GO_coad_tn$P.DE),]
head(as.matrix(enrichment_GO_coad_tn), 10)
```

```{r LUAD}
#BiocManager::install("DMRcate")
library(DMRcate)
type_luad_tn <- factor(luad_data_m$definition)
design_luad_tn <- model.matrix(~type_luad_tn)
myannotation_luad_tn <- cpg.annotate("array", assay(luad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_luad_tn, coef=2)
myannotation_luad_tn

dmrcoutput_luad_tn <- dmrcate(myannotation_luad_tn, lambda=1000, C=2)

results.ranges_luad_tn <- extractRanges(dmrcoutput_luad_tn, genome = "hg19")
results.ranges_luad_tn
results.ranges_luad_tn[c(1:5), c(1,5,8)]

groups_luad_tn <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_luad_tn <- groups_luad_tn[as.character(type_luad_tn)]
DMR.plot(ranges=results.ranges_luad_tn, dmr=1, CpGs=assay(luad_data_m), what="M",
arraytype = "450K", phen.col=cols_luad_tn, genome="hg19")

library(missMethyl)
enrichment_GO_luad_tn <- goregion(results.ranges_luad_tn, all.cpg = rownames(luad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_luad_tn <- enrichment_GO_luad_tn[order(enrichment_GO_luad_tn$P.DE),]
head(as.matrix(enrichment_GO_luad_tn), 10)
```
