---
title: "Identificación DMRs Edad"
author: "Ana Diez Borge"
date: "13 de diciembre de 2020"
output: html_document
---

```{r Cargamos datos de metilación}
Data_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio"
Results_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio/Results"
setwd(Data_dir)
coad_data = readRDS(file = "coad_data.RDS")
lihc_data = readRDS(file = "lihc_data.RDS")
paad_data = readRDS(file = "paad_data.RDS")
luad_data = readRDS(file = "luad_data.RDS")
```


```{r Transformamos beta-values a M-values}
#En este caso para aumentar la fiabilidad del estudio se transforman los b-value a M-value
#Para obtener los M-values creo una la funcion mvalues
mvalues <- function(bvalue) {
      m <- log2(bvalue/(1 - bvalue))
      return(m)}

paad_mvalues <- apply(assay(paad_data), c(1,2), mvalues)
lihc_mvalues <- apply(assay(lihc_data), c(1,2), mvalues)
coad_mvalues <- apply(assay(coad_data), c(1,2), mvalues)
luad_mvalues <- apply(assay(luad_data), c(1,2), mvalues)

paad_data_m <- paad_data
lihc_data_m <- lihc_data
coad_data_m <- coad_data
luad_data_m <- luad_data

assay(paad_data_m) = paad_mvalues
assay(lihc_data_m) = lihc_mvalues
assay(coad_data_m) = coad_mvalues
assay(luad_data_m) = luad_mvalues
```

```{r PAAD age}
library(DMRcate)
type_paad <- factor(paad_data_m$definition)
age_paad <- factor(paad_data_m$age_at_index)
design_paad_age <- model.matrix(~type_paad:age_paad)
myannotation_paad_age <- cpg.annotate("array", assay(paad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_paad_age, coef=2)
myannotation_paad_age

dmrcoutput_paad_age <- dmrcate(myannotation_paad_age, lambda=1000, C=2)

results.ranges_paad_age <- extractRanges(dmrcoutput_paad_age, genome = "hg19")

groups_paad_age <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue" )
cols_paad_age <- groups_paad_age[as.character(type_paad_age)]
DMR.plot(ranges=results.ranges_paad_age, dmr=3, CpGs=assay(paad_data_m), what="M",
arraytype = "450K", phen.col=cols_paad_age, genome="hg19")

library(missMethyl)
enrichment_GO_paad_age <- goregion(results.ranges_paad_age, all.cpg = rownames(paad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_paad_age <- enrichment_GO_paad_age[order(enrichment_GO_paad_age$P.DE),]
head(as.matrix(enrichment_GO_paad_age), 10)
```

```{r LIHC}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_lihc_age <- factor(lihc_data_m$definition)
age_lihc <- factor(lihc_data_m$age_at_index)
design_lihc_age <- model.matrix(~type_lihc:age_lihc)
myannotation_lihc_age <- cpg.annotate("array", assay(lihc_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_lihc_age, coef=2)

dmrcoutput_lihc_age <- dmrcate(myannotation_lihc_age, lambda=1000, C=2)

results.ranges_lihc_age <- extractRanges(dmrcoutput_lihc_age, genome = "hg19")
results.ranges_lihc_age[c(1:5), c(1,5,8)]

groups_lihc_age <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue" )
cols_lihc_age <- groups_lihc_age[as.character(type_lihc_age)]
DMR.plot(ranges=results.ranges_lihc_age, dmr=6, CpGs=assay(lihc_data_m), what="M",
arraytype = "450K", phen.col=cols_lihc_age, genome="hg19")

enrichment_GO_lihc_age <- goregion(results.ranges_lihc_age, all.cpg = rownames(lihc_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_lihc_age <- enrichment_GO_lihc_age[order(enrichment_GO_lihc_age$P.DE),]
head(as.matrix(enrichment_GO_lihc_age), 10)
```

```{r COAD}
#BiocManager::install("DMRcate")
library(DMRcate)
library(missMethyl)

type_coad_age <- factor(coad_data_m$definition)
age_coad <- factor(coad_data_m$age_at_index)
design_coad_age <- model.matrix(~type_coad:age_coad)
myannotation_coad_age <- cpg.annotate("array", assay(coad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_coad_age, coef=2)

dmrcoutput_coad_age <- dmrcate(myannotation_coad_age, lambda=1000, C=2)

results.ranges_coad_age <- extractRanges(dmrcoutput_coad_age, genome = "hg19")
results.ranges_coad_age

groups_coad_age <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_coad_age <- groups_coad_age[as.character(type_coad_age)]
DMR.plot(ranges=results.ranges_coad_age, dmr=1000, CpGs=assay(coad_data_age), what="M",
arraytype = "450K", phen.col=cols_coad_age, genome="hg19")

enrichment_GO_coad_age <- goregion(results.ranges_coad_age, all.cpg = rownames(coad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_coad_age <- enrichment_GO_coad_age[order(enrichment_GO_coad_age$P.DE),]
head(as.matrix(enrichment_GO_coad_age), 10)
```

```{r LUAD}
#BiocManager::install("DMRcate")
library(DMRcate)
type_luad_age <- factor(luad_data_m$definition)
age_luad <- factor(luad_data_m$age_at_index)
design_luad_age <- model.matrix(~type_luad:age_luad)
myannotation_luad_age <- cpg.annotate("array", assay(luad_data_m),what = "M", arraytype = "450K",
analysis.type="differential", design=design_luad_age, coef=2)

dmrcoutput_luad_age <- dmrcate(myannotation_luad_age, lambda=1000, C=2)

results.ranges_luad_age <- extractRanges(dmrcoutput_luad_age, genome = "hg19")
results.ranges_luad_age
results.ranges_luad_age[c(1:5), c(1,5,8)]

groups_luad_age <- c("Primary solid Tumor"= "red", "Solid Tissue Normal" = "blue")
cols_luad_age <- groups_luad[as.character(type_luad_age)]
DMR.plot(ranges=results.ranges_luad_age, dmr=1, CpGs=assay(luad_data_age), what="M",
arraytype = "450K", phen.col=cols_luad_age, genome="hg19")

library(missMethyl)
enrichment_GO_luad_age <- goregion(results.ranges_luad_age, all.cpg = rownames(luad_data_m),
collection = "GO", array.type = "450K")
enrichment_GO_luad_age <- enrichment_GO_luad_age[order(enrichment_GO_luad_age$P.DE),]
head(as.matrix(enrichment_GO_luad_age), 10)
```
