---
title: "Descarga muestras N y T"
author: "Ana Diez Borge"
date: "17 de septiembre de 2020"
output: html_document
lang: es
output: 
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    toc_depth: 4
    code_download: true
---

### SELECCIÓN DE MUESTRAS N Y T COAD ###

```{r COAD} 
setwd("./Rstudio")
#BiocManager::install("GenomicDataCommons")
library(GenomicDataCommons)
library(dplyr)

#Filtramos muestras de metilacion de tejido normal
nl_met_files_COAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Solid Tissue Normal' &
               cases.project.project_id == 'TCGA-COAD' &
               #data_type == "Methylation Beta Value") 
               platform == "Illumina Human Methylation 450") %>%  
               
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Filtramos muestras de metilacion de tejido tumoral
tm_met_files_COAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Primary Tumor' &
               cases.project.project_id == 'TCGA-COAD' &
               #data_type == "Methylation Beta Value") 
               platform == "Illumina Human Methylation 450") %>% 
               
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Nos quedamos solo con muestras de pacientes con tejido normal y tumoral
nl_cases_COAD = bind_rows(nl_met_files_COAD$cases, .id='file_id')
tm_cases_COAD = bind_rows(tm_met_files_COAD$cases, .id='file_id')
matchedcases_COAD = intersect(nl_cases_COAD$case_id, tm_cases_COAD$case_id)
COAD <- length(matchedcases_COAD) 

#Creamos data frame con muestras n y t apareadas
matched_nl_files_COAD = nl_cases_COAD[nl_cases_COAD$case_id %in% matchedcases_COAD, 'file_id']
matched_tm_files_COAD = tm_cases_COAD[tm_cases_COAD$case_id %in% matchedcases_COAD, 'file_id']

matched_tn_met_file_info_COAD = rbind(subset(nl_met_files_COAD,file_id %in% matched_nl_files_COAD),subset(tm_met_files_COAD,file_id %in% matched_tm_files_COAD))
head(matched_tn_met_file_info_COAD)

#Guardamos data frame
muestras_COAD = data.frame(lapply(matched_tn_met_file_info_COAD, as.character), stringsAsFactors=FALSE)
#write.txt("muestras_COAD.txt")
write.table(muestras_COAD, file = "muestras_COAD.txt", sep = "\t", col.names = TRUE, row.names = TRUE, quote = F)
```

### SELECCIÓN DE MUESTRAS N Y T LIHC ###

```{r LIHC} 
setwd("./Rstudio")
#BiocManager::install("GenomicDataCommons")
library(GenomicDataCommons)
library(dplyr)

#Filtramos muestras de metilacion de tejido normal
nl_met_files_LIHC = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Solid Tissue Normal' &
               cases.project.project_id == 'TCGA-LIHC' &
               #data_type == "Methylation Beta Value") %>%
               platform == "Illumina Human Methylation 450") %>%  
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Filtramos muestras de metilacion de tejido tumoral
tm_met_files_LIHC = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Primary Tumor' &
               cases.project.project_id == 'TCGA-LIHC' &
               #data_type == "Methylation Beta Value") %>%
               platform == "Illumina Human Methylation 450") %>% 
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Nos quedamos solo con muestras de pacientes con tejido normal y tumoral
nl_cases_LIHC = bind_rows(nl_met_files_LIHC$cases, .id='file_id')
tm_cases_LIHC = bind_rows(tm_met_files_LIHC$cases, .id='file_id')
matchedcases_LIHC = intersect(nl_cases_LIHC$case_id, tm_cases_LIHC$case_id)
LIHC <- length(matchedcases_LIHC) 

#Creamos data frame con muestras n y t apareadas
matched_nl_files_LIHC = nl_cases_LIHC[nl_cases_LIHC$case_id %in% matchedcases_LIHC, 'file_id']
matched_tm_files_LIHC = tm_cases_LIHC[tm_cases_LIHC$case_id %in% matchedcases_LIHC, 'file_id']

matched_tn_met_file_info_LIHC = rbind(subset(nl_met_files_LIHC,file_id %in% matched_nl_files_LIHC),subset(tm_met_files_LIHC,file_id %in% matched_tm_files_LIHC))
head(matched_tn_met_file_info_LIHC)

#Guardamos data frame
muestras_LIHC = data.frame(lapply(matched_tn_met_file_info_LIHC, as.character), stringsAsFactors=FALSE)
#write.txt("muestras_LIHC.txt")
write.table(muestras_LIHC, file = "muestras_LIHC.txt", sep = "\t", col.names = TRUE, row.names = TRUE, quote = F)
```

### SELECCIÓN DE MUESTRAS N Y T LUAD ###

```{r LUAD} 
setwd("./Rstudio")
#BiocManager::install("GenomicDataCommons")
library(GenomicDataCommons)
library(dplyr)

#Filtramos muestras de metilacion de tejido normal
nl_met_files_LUAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Solid Tissue Normal' &
               cases.project.project_id == 'TCGA-LUAD' &
               #data_type == "Methylation Beta Value") %>%
                platform == "Illumina Human Methylation 450") %>%
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Filtramos muestras de metilacion de tejido tumoral
tm_met_files_LUAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Primary Tumor' &
               cases.project.project_id == 'TCGA-LUAD' &
               #data_type == "Methylation Beta Value") %>%
                platform == "Illumina Human Methylation 450") %>%       
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Nos quedamos solo con muestras de pacientes con tejido normal y tumoral
nl_cases_LUAD = bind_rows(nl_met_files_LUAD$cases, .id='file_id')
tm_cases_LUAD = bind_rows(tm_met_files_LUAD$cases, .id='file_id')
matchedcases_LUAD = intersect(nl_cases_LUAD$case_id, tm_cases_LUAD$case_id)
LUAD <- length(matchedcases_LUAD) 

#Creamos data frame con muestras n y t apareadas
matched_nl_files_LUAD = nl_cases_LUAD[nl_cases_LUAD$case_id %in% matchedcases_LUAD, 'file_id']
matched_tm_files_LUAD = tm_cases_LUAD[tm_cases_LUAD$case_id %in% matchedcases_LUAD, 'file_id']

matched_tn_met_file_info_LUAD = rbind(subset(nl_met_files_LUAD,file_id %in% matched_nl_files_LUAD),subset(tm_met_files_LUAD,file_id %in% matched_tm_files_LUAD))
head(matched_tn_met_file_info_LUAD)

#Guardamos data frame
muestras_LUAD = data.frame(lapply(matched_tn_met_file_info_LUAD, as.character), stringsAsFactors=FALSE)
#write.txt("muestras_LUAD.txt")
write.table(muestras_LUAD, file = "muestras_LUAD.txt", sep = "\t", col.names = TRUE, row.names = TRUE, quote = F)
```

### SELECCIÓN DE MUESTRAS N Y T PAAD ###

```{r PAAD} 
setwd("./Rstudio")
#BiocManager::install("GenomicDataCommons")
library(GenomicDataCommons)
library(dplyr)

#Filtramos muestras de metilacion de tejido normal
nl_met_files_PAAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Solid Tissue Normal' &
               cases.project.project_id == 'TCGA-PAAD' &
               #data_type == "Methylation Beta Value") 
               platform == "Illumina Human Methylation 450") %>%
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Filtramos muestras de metilacion de tejido tumoral
tm_met_files_PAAD = files() %>%
    GenomicDataCommons::filter(~cases.samples.sample_type=='Primary Tumor' &
               cases.project.project_id == 'TCGA-PAAD' &
               #data_type == "Methylation Beta Value")
               platform == "Illumina Human Methylation 450") %>%
    expand(c('cases','cases.samples')) %>%
    results_all() %>%
    as_tibble()

#Nos quedamos solo con muestras de pacientes con tejido normal y tumoral
nl_cases_PAAD = bind_rows(nl_met_files_PAAD$cases, .id='file_id')
tm_cases_PAAD = bind_rows(tm_met_files_PAAD$cases, .id='file_id')
matchedcases_PAAD = intersect(nl_cases_PAAD$case_id, tm_cases_PAAD$case_id)
PAAD <- length(matchedcases_PAAD) 

#Creamos data frame con muestras n y t apareadas
matched_nl_files_PAAD = nl_cases_PAAD[nl_cases_PAAD$case_id %in% matchedcases_PAAD, 'file_id']
matched_tm_files_PAAD = tm_cases_PAAD[tm_cases_PAAD$case_id %in% matchedcases_PAAD, 'file_id']

matched_tn_met_file_info_PAAD = rbind(subset(nl_met_files_PAAD,file_id %in% matched_nl_files_PAAD),subset(tm_met_files_PAAD,file_id %in% matched_tm_files_PAAD))
head(matched_tn_met_file_info_PAAD)

#Guardamos data frame
muestras_PAAD = data.frame(lapply(matched_tn_met_file_info_LUAD, as.character), stringsAsFactors=FALSE)

#write.txt("muestras_PAAD.txt")
write.table(muestras_PAAD, file = "muestras_PAAD.txt", sep = "\t", col.names = TRUE, row.names = TRUE, quote = F) 
                  
```

# NUMERO DE PACIENTES CON MUESTRAS N Y T

```{r}
COAD
LIHC
LUAD
PAAD
```

### SELECCION DE BARCODES DE PACIENTES DE INTERES ###

```{r seleccion solo de barcodes}
#install.packages("tidyverse")
library(tidyverse)
setwd("~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio")
barcodes_paad <- str_sub(matched_tn_met_file_info_PAAD$file_name, 46, 64)
barcodes_paad
write.table(barcodes_paad, file = "barcodes_paad.txt", sep = ",", col.names = FALSE, row.names = FALSE, quote = F)

barcodes_coad <- str_sub(matched_tn_met_file_info_COAD$file_name, 46, 64)
barcodes_coad
write.table(barcodes_coad, file = "barcodes_coad.txt", sep = ",", col.names = FALSE, row.names = FALSE, quote = F)

barcodes_LIHC <- str_sub(matched_tn_met_file_info_LIHC$file_name, 46, 64)
barcodes_LIHC
write.table(barcodes_LIHC, file = "barcodes_lihc.txt", sep = "\t", col.names = FALSE, row.names = FALSE, quote = F)

barcodes_LUAD <- str_sub(matched_tn_met_file_info_LUAD$file_name, 46, 64)
barcodes_LUAD
write.table(barcodes_LUAD, file = "barcodes_luad.txt", sep = "\t", col.names = FALSE, row.names = FALSE, quote = F)

```

### DESCARGA DE DATOS A PARTIR DE LOS BARCODES ###

```{r Descarga}
setwd("./Rstudio")
library(TCGAbiolinks)
coad <- "TCGA-COAD"
query.met.coad <- GDCquery(project = coad,
                  legacy = TRUE,
                  data.category = "DNA methylation",
                  platform = "Illumina Human Methylation 450",
                  sample.type = c("Primary Tumor", "Solid Tissue Normal"),
                  barcode = barcodes_coad)

#GDCdownload(query.met.coad_prueba)

```

```{r Descarga PAAD}
setwd("./Rstudio")
library(TCGAbiolinks)
paad <- "TCGA-PAAD"
query.met.paad <- GDCquery(project = paad,
                  legacy = TRUE,
                  data.category = "DNA methylation",
                  platform = "Illumina Human Methylation 450",
                  sample.type = c("Primary Tumor", "Solid Tissue Normal"),
                  barcode = barcodes_paad)

#GDCdownload(query.met.paad_prueba)

```
```{r Descarga PAAD}
setwd("./Rstudio")
library(TCGAbiolinks)
lihc <- "TCGA-LIHC"
query.met.lihc <- GDCquery(project = lihc,
                  legacy = TRUE,
                  data.category = "DNA methylation",
                  platform = "Illumina Human Methylation 450",
                  sample.type = c("Primary Tumor", "Solid Tissue Normal"),
                  barcode = barcodes_LIHC)

#GDCdownload(query.met.lihc_prueba)

```
```{r Descarga PAAD}
setwd("./Rstudio")
library(TCGAbiolinks)
luad <- "TCGA-LUAD"
query.met.luad <- GDCquery(project = luad,
                  legacy = TRUE,
                  data.category = "DNA methylation",
                  platform = "Illumina Human Methylation 450",
                  sample.type = c("Primary Tumor", "Solid Tissue Normal"),
                  barcode = barcodes_LUAD)

#GDCdownload(query.met.luad_prueba)

```

```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)
setwd("./Rstudio")
coad_data = GDCprepare(query.met.coad)
dim(tcga_data)
#colnames(colData(tcga_data))
tcga_data$gender
table(coad_data$gender)
```

```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)
setwd("./Rstudio")
luad_data = GDCprepare(query.met.luad)
dim(luad_data)
#colnames(colData(tcga_data))
luad_data$gender
table(luad_data$gender)
```

```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)
setwd("./Rstudio")
paad_data = GDCprepare(query.met.paad)
dim(paad_data)
#colnames(colData(tcga_data))
paad_data$gender
table(paad_data$gender)
```

```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)
setwd("./Rstudio")
lihc_data = GDCprepare(query.met.lihc)
dim(lihc_data)
#colnames(colData(tcga_data))
lihc_data$gender
table(lihc_data$gender)
```

```{r}
COAD
table(coad_data$gender)

LUAD
table(luad_data$gender)

LIHC
table(lihc_data$gender)

PAAD
table(paad_data$gender)
```

```{r Guardamos los datos en archivos RDS}
saveRDS(object = coad_data,
        file = "coad_data.RDS",
        compress = FALSE)

saveRDS(object = paad_data,
        file = "paad_data.RDS",
        compress = FALSE)

saveRDS(object = lihc_data,
        file = "lihc_data.RDS",
        compress = FALSE)

saveRDS(object = luad_data,
        file = "luad_data.RDS",
        compress = FALSE)

```


