---
title: "Previsualizacion Datos"
author: "Ana Diez Borge"
date: "13 de noviembre de 2020"
output: html_document
---

```{r Cargamos datos de metilación}
Data_dir <- "~/Master UOC - Bioinfo y bioestadistica/TFM/Rstudio"
setwd(Data_dir)
coad_data = readRDS(file = "coad_data.RDS")
lihc_data = readRDS(file = "lihc_data.RDS")
paad_data = readRDS(file = "paad_data.RDS")
luad_data = readRDS(file = "luad_data.RDS")
```

##PREPROCESAMIENTO DE LOS DATOS##
```{r}
dim(coad_data)
dim(luad_data)
dim(paad_data)
dim(lihc_data)
```

```{r}
#Eliminamos todos los NA
coad_data <- subset(coad_data,subset = (rowSums(is.na(assay(coad_data))) == 0))
lihc_data <- subset(lihc_data,subset = (rowSums(is.na(assay(lihc_data))) == 0))
paad_data <- subset(paad_data,subset = (rowSums(is.na(assay(paad_data))) == 0))
luad_data <- subset(luad_data,subset = (rowSums(is.na(assay(luad_data))) == 0))

dim(coad_data)
dim(luad_data)
dim(paad_data)
dim(lihc_data)
```

```{r Se eliminan los datos pertenecientes a los cromosomas sexuales}
coad_data <- subset(coad_data,subset = !as.character(seqnames(coad_data)) %in% c("chrNA","chrX","chrY"))
dim(coad_data)

lihc_data <- subset(lihc_data,subset = !as.character(seqnames(lihc_data)) %in% c("chrNA","chrX","chrY"))
dim(lihc_data)

paad_data <- subset(paad_data,subset = !as.character(seqnames(paad_data)) %in% c("chrNA","chrX","chrY"))
dim(paad_data)

luad_data <- subset(luad_data,subset = !as.character(seqnames(luad_data)) %in% c("chrNA","chrX","chrY"))
dim(luad_data)
```

```{r Previsualizacion de datos density plot}
#install.packages("car")
library(car)
par(mfrow = c(2,2))
densityPlot(assay(paad_data),legend = TRUE, main = "PAAD beta-values")
densityPlot(assay(coad_data), legend = TRUE, main = "COAD beta-values")
densityPlot(assay(lihc_data), legend = TRUE, main = "LIHC beta-values")
densityPlot(assay(luad_data),legend = TRUE, main = "LUAD beta-values")
```


```{r qlots}
library(ggplot2)
#PAAD tejido tumoral y normal
qplot(assay(paad_data)[ , grepl( "01A" , colnames( assay(paad_data) ) ) ] , fill=I(rgb(0.72, 0.201, 0.176,0.6)), main = "Tejido Tumoral PAAD", xlab = "Beta-values", ylab = "Count", bins = 50)
qplot(assay(paad_data)[ , grepl( "11A" , colnames( assay(paad_data) ) ) ] , fill=I(rgb(0.1,0.2,0.4,0.6)), main = "Tejido Normal PAAD", xlab = "Beta-values", ylab = "Count", bins = 50)

#LUAD tejido tumoral y normal
qplot(assay(luad_data)[ , grepl( "01A" , colnames( assay(luad_data) ) ) ] , fill=I(rgb(0.72, 0.201, 0.176,0.6)), main = "Tejido Tumoral LUAD", xlab = "Beta-values", ylab = "Count", bins = 50)

qplot(assay(luad_data)[ , grepl( "11A" , colnames( assay(luad_data) ) ) ] , fill=I(rgb(0.1,0.2,0.4,0.6)), main = "Tejido Normal LUAD", xlab = "Beta-values", ylab= "Count", bins = 50 )


#LIHC tejido tumoral y normal
qplot(assay(lihc_data)[ , grepl( "01A" , colnames( assay(lihc_data) ) ) ] , fill=I(rgb(0.72, 0.201, 0.176,0.6)), main = "Tejido Tumoral LIHC", xlab = "Beta-values", ylab = "Count", bins = 50)

qplot(assay(lihc_data)[ , grepl( "11A" , colnames( assay(lihc_data) ) ) ] , fill=I(rgb(0.1,0.2,0.4,0.6)), main = "Tejido Normal LIHC", xlab = "Beta-values", ylab= "Count", bins = 50 )

#COAD tejido tumoral y normal
qplot(assay(coad_data)[ , grepl( "01A" , colnames( assay(coad_data) ) ) ] , fill=I(rgb(0.72, 0.201, 0.176,0.6)), main = "Tejido Tumoral COAD", xlab = "Beta-values", ylab = "Count", bins = 50)

qplot(assay(coad_data)[ , grepl( "11A" , colnames( assay(coad_data) ) ) ] , fill=I(rgb(0.1,0.2,0.4,0.6)), main = "Tejido Normal COAD", xlab = "Beta-values", ylab= "Count", bins = 50 )

```


```{r Diferencias entre medias de metilacion Norm-Tum}
library(TCGAbiolinks)
setwd(Data_dir)
TCGAvisualize_meanMethylation(paad_data,
                              groupCol = "definition",
                              group.legend = "Groups",
                              title = "Mean DNA methylation PAAD",
                              print.pvalue = TRUE,
                              filename = 'methylationMean_PAAD_norm-tum.png')

TCGAvisualize_meanMethylation(lihc_data,
                              groupCol = "definition",
                              group.legend = "Groups",
                              title = "Mean DNA methylation LIHC",
                              print.pvalue = TRUE,
                              filename = 'methylationMean_LIHC_norm-tum.png')

TCGAvisualize_meanMethylation(luad_data,
                              groupCol = "definition",
                              group.legend = "Groups",
                              title = "Mean DNA methylation LUAD",
                              print.pvalue = TRUE,
                              filename = 'methylationMean_LUAD_norm-tum.png')

TCGAvisualize_meanMethylation(coad_data,
                              groupCol = "definition",
                              group.legend = "Groups",
                              title = "Mean DNA methylation COAD",
                              print.pvalue = TRUE,
                              filename = 'methylationMean_COAD_norm-tum.png')
```

```{r Diferencias entre medias de metilacion Norm-Tum Covariable Sexo}
library(TCGAbiolinks)
setwd(Data_dir)
#Separamos los datos en función del género del paciente

#PAAD
TCGAvisualize_meanMethylation(paad_data[paad_data$gender == "male"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation PAAD Male",
                              filename = 'methylationMean_PAAD_male_norm-tum.png')

TCGAvisualize_meanMethylation(paad_data[paad_data$gender == "female"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation PAAD Female",
                              filename = 'methylationMean_PAAD_female_norm-tum.png')

#LIHC
TCGAvisualize_meanMethylation(lihc_data[lihc_data$gender == "male"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation LIHC Male",
                              filename = 'methylationMean_LIHC_male_norm-tum.png')

TCGAvisualize_meanMethylation(lihc_data[lihc_data$gender == "female"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation LIHC Female",
                              filename = 'methylationMean_LIHC_female_norm-tum.png')

#LUAD
TCGAvisualize_meanMethylation(luad_data[luad_data$gender == "male"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation LUAD Male",
                              filename = 'methylationMean_LUAD_male_norm-tum.png')

TCGAvisualize_meanMethylation(luad_data[luad_data$gender == "female"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation LUAD Female",
                              filename = 'methylationMean_LUAD_female_norm-tum.png')

#COAD
TCGAvisualize_meanMethylation(coad_data[coad_data$gender == "male"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation COAD Male",
                              filename = 'methylationMean_COAD_Male_norm-tum.png')

TCGAvisualize_meanMethylation(coad_data[coad_data$gender == "female"],
                              groupCol = "definition",
                              group.legend = "Groups",
                              print.pvalue = TRUE,
                              title = "Mean DNA methylation COAD Female",
                              filename = 'methylationMean_COAD_female_norm-tum.png')
```

```{r Diferencias entre medias de metilacion Norm-Tum Covariable Edad}
library(TCGAbiolinks)
setwd(Results_dir)
#PAAD
TCGAvisualize_meanMethylation(paad_data[paad_data$definition == "Primary solid Tumor"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Tumor PAAD",
                               filename = 'methylationMean_PAAD_age_tum.png')

TCGAvisualize_meanMethylation(paad_data[paad_data$definition == "Solid Tissue Normal"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Normal PAAD",
                               filename = 'methylationMean_PAAD_age_norm.png')

#COAD
TCGAvisualize_meanMethylation(coad_data[coad_data$definition == "Primary solid Tumor"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Tumor COAD",
                               filename = 'methylationMean_COAD_age_tum.png')

TCGAvisualize_meanMethylation(coad_data[coad_data$definition == "Solid Tissue Normal"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Normal COAD",
                               filename = 'methylationMean_COAD_age_norm.png')

#LIHC
TCGAvisualize_meanMethylation(lihc_data[lihc_data$definition == "Primary solid Tumor"],
                               groupCol = "age_at_index",
                               group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Tumor LIHC",
                               filename = 'methylationMean_LIHC_age_tum.png')

TCGAvisualize_meanMethylation(lihc_data[lihc_data$definition == "Solid Tissue Normal"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Normal LIHC",
                               filename = 'methylationMean_LIHC_age_norm.png')

#LUAD
TCGAvisualize_meanMethylation(luad_data[luad_data$definition == "Primary solid Tumor"],
                               groupCol = "age_at_index",
                               #group.legend = "Groups",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Tumor LUAD",
                               filename = 'methylationMean_LUAD_age_tum.png')

TCGAvisualize_meanMethylation(luad_data[luad_data$definition == "Solid Tissue Normal"],
                               groupCol = "age_at_index",
                               print.pvalue = TRUE,
                               title = "Mean DNA methylation Age Normal LUAD",
                               filename = 'methylationMean_LUAD_age_norm.png')

```



